export const UPDATE_HEIGHT_ABOUT = 'UPDATE_HEIGHT_ABOUT';
export const UPDATE_HEIGHT_EXP = 'UPDATE_HEIGHT_EXP';
export const UPDATE_HEIGHT_SKILLS = 'UPDATE_HEIGHT_SKILLS';
export const UPDATE_HEIGHT_4 = 'UPDATE_HEIGHT_4';